DROP PROCEDURE IF EXISTS populate_studytools_procedure;
delimiter //
CREATE PROCEDURE populate_studytools_procedure()
BEGIN
	INSERT INTO studytools VALUES ('1015 Grove Ave., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('1015 Grove Ave., Richmond, VA 23220', 'Coffee');
	INSERT INTO studytools VALUES ('1015 Grove Ave., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('1015 Grove Ave., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('609 Bowe St., Richmond, VA 23220', 'Printer');
	INSERT INTO studytools VALUES ('609 Bowe St., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('1315 Floyd Ave., Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('1315 Floyd Ave., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('1315 Floyd Ave., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('10 N. Brunswick St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('10 N. Brunswick St., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('10 N. Brunswick St., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('10 N. Brunswick St., Richmond, VA 23220', '3D Printer');
	INSERT INTO studytools VALUES ('1000 W. Broad St., Richmond, VA 23220', 'Printer');
	INSERT INTO studytools VALUES ('801 W. Marshall St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('801 W. Marshall St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('801 W. Marshall St., Richmond, VA 23220', '3D Printer');
	INSERT INTO studytools VALUES ('814 W. Broad St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('814 W. Broad St., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('814 W. Broad St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('814 W. Broad St., Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('812-814 W. Franklin St., Richmond, VA 23220', 'Printer');
	INSERT INTO studytools VALUES ('812-814 W. Franklin St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('812-814 W. Franklin St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('812-814 W. Franklin St., Richmond, VA 23220', '3D Printer');
	INSERT INTO studytools VALUES ('419 W. Broad St, Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('419 W. Broad St, Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('325 N. Harrison St., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('325 N. Harrison St., Richmond, VA 23220', 'Coffee');
	INSERT INTO studytools VALUES ('325 N. Harrison St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('922 Park Ave., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('301 W. Main St., Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('301 W. Main St., Richmond, VA 23220', 'Coffee');
	INSERT INTO studytools VALUES ('301 W. Main St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('301 W. Main St., Richmond, VA 23220', '3D Printer');
	INSERT INTO studytools VALUES ('101 N. Harrison St., Richmond, VA 23220', 'Printer');
	INSERT INTO studytools VALUES ('101 N. Harrison St., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('101 N. Harrison St., Richmond, VA 23220', 'Coffee');
	INSERT INTO studytools VALUES ('1015 W. Main St., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('401 W. Main St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('401 W. Main St., Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('401 W. Main St., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('401 W. Main St., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('601 W. Main St., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('601 W. Main St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('601 W. Main St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('1015 Floyd Ave., Richmond, VA 23220', '3D Printer');
	INSERT INTO studytools VALUES ('1015 Floyd Ave., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('1015 Floyd Ave., Richmond, VA 23220', 'Coffee');
	INSERT INTO studytools VALUES ('1015 Floyd Ave., Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('1015 Floyd Ave., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('900 Park Ave., Richmond, VA 23220', '3D Printer');
	INSERT INTO studytools VALUES ('900 Park Ave., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('900 Park Ave., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('900 Park Ave., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('701 W. Grace St., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('701 W. Grace St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('701 W. Grace St., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('701 W. Grace St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('103 S. Jefferson St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('1001 W. Main St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('1001 W. Main St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('901 W. Main St., Richmond, VA 23220', 'Quiet Room');
	INSERT INTO studytools VALUES ('901 W. Main St., Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('901 W. Main St., Richmond, VA 23220', 'Copier');
	INSERT INTO studytools VALUES ('901 W. Main St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('1000 W. Cary St., Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('1000 W. Cary St., Richmond, VA 23220', 'Coffee');
	INSERT INTO studytools VALUES ('1000 W. Cary St., Richmond, VA 23220', 'Printer');
	INSERT INTO studytools VALUES ('1000 W. Cary St., Richmond, VA 23220', 'White Board');
	INSERT INTO studytools VALUES ('1000 W. Cary St., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('103 S. Jefferson St., Richmond, VA 23220', 'Computer');
	INSERT INTO studytools VALUES ('901 W. Main St., Richmond, VA 23220', 'Printer');
	INSERT INTO studytools VALUES ('901 W. Main St., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('1000 Floyd Ave., Richmond, VA 23220', 'Projector');
	INSERT INTO studytools VALUES ('1000 Floyd Ave., Richmond, VA 23220', '3D Printer');
	INSERT INTO studytools VALUES ('1000 Floyd Ave., Richmond, VA 23220', 'Coffee');
END //
delimiter ;
